# Generated by Django 2.1 on 2018-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
